### ISSUE TITLE
Error with the code

### ISSUE THREAD

**Issue by lrc9859** [mtoneva/example_forgetting#7]
I tried running the code and got this error.
"Traceback (most recent call last):
  File "run_mnist.py", line 332, in <module>
    trainset.train_data = trainset.train_data[train_indx, :, :]
AttributeError: can't set attribute"

**Comment by CFP2023** [comment]
May I ask if you have solved the problem

**Comment by aymuos15** [comment]
`python run_mnist.py --dataset mnist --no_dropout --output_dir mnist_results --seed 1
`

```
{'dataset': 'mnist', 'batch_size': 64, 'epochs': 200, 'lr': 0.01, 'momentum': 0.5, 'no_cuda': False, 'seed': 1, 'sorting_file': 'none', 'remove_n': 0, 'keep_lowest_n': 0, 'no_dropout': True, 'input_dir': 'mnist_results/', 'output_dir': 'mnist_results'}
/home/localssk23/backup/soumya/env/ppml/lib/python3.10/site-packages/torchvision/datasets/mnist.py:66: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")
/home/localssk23/backup/soumya/env/ppml/lib/python3.10/site-packages/torchvision/datasets/mnist.py:76: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")

```
```
Traceback (most recent call last):
  File "/home/localssk23/example_forgetting/run_mnist.py", line 332, in <module>
    trainset.train_data = trainset.train_data[train_indx, :, :]
AttributeError: can't set attribute 'train_data'
```

Still the same issue :(
